name: Python Tests
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Checks unittest


    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: "**/*.py"

      - name: Set up Python all python version
        if: steps.changed-files.output.any_changed == 'true'
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        if: steps.changed-files.output.any_changed == 'true'
        run: sudo apt-get install libgirepository1.0-dev

      - run: pip install --upgrade pip
        if: steps.changed-files.output.any_changed == 'true'
      - run: pip install .
        if: steps.changed-files.output.any_changed == 'true'

      - name: Run Test
        if: steps.changed-files.output.any_changed == 'true'
        run: coverage run -m unittest

      - name: Create coverage xml
        if: steps.changed-files.output.any_changed == 'true'
        run: coverage xml coverage.xml

      - name: Get Cover
        uses: orgoro/coverage@v3.1
        with:
            coverageFile: coverage.xml
            token: ${{ secrets.GITHUB_TOKEN }}
